### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by UcraNerd** [TangoBeee/Weathernaut#3]
When I open the app, it crashes immediately.
Android 13.

**Comment by TangoBeee** [comment]
Do you see any errors?
And does this happen every time?

**Comment by UcraNerd** [comment]
Why there are two versions by the way?

**Comment by TangoBeee** [comment]
Version 1.1 is the older version which has some bugs and version 1.3 is the latest version.

**Comment by UcraNerd** [comment]
> Version 1.1 is the older version which has some bugs and version 1.3 is the latest version.

I meant why there are two different apk in the release

**Comment by UcraNerd** [comment]
> Do you see any errors?
> And does this happen every time?

There are no app's internal errors and it happens all the time.

**Comment by manangupta** [comment]
I faced this not being copied to studio, saying signing.properties is missing

**Comment by TangoBeee** [comment]
Hi @manangupta,
I know there are a lot of bugs in the previous version. So, that's why I'm working on version 2 of the app.
It will be released in a few days.
